name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  vft-service:
      name: VftService
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install Clippy
        run: rustup component add clippy

      - name: Install Rustfmt
        run: rustup component add rustfmt

      - name: Check formatting
        run: cargo fmt --all --manifest-path vft-service/Cargo.toml -- --check

      - name: Run Clippy
        run: cargo clippy -r --manifest-path vft-service/Cargo.toml -- -D warnings

  extend-vft:
    needs: [vft-service]
    name: ExtendVft
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true

    - name: Install Clippy
      run: rustup component add clippy

    - name: Install Rustfmt
      run: rustup component add rustfmt

    - name: Check formatting
      run: cargo fmt --all --manifest-path extended-vft/Cargo.toml -- --check

    - name: Run Clippy
      run: cargo clippy -r --manifest-path extended-vft/Cargo.toml -- -D warnings

    - name: Prepare environment
      run: |
        mkdir -p extended-vft/target/tmp
        curl -L https://get.gear.rs/gear-v1.4.2-x86_64-unknown-linux-gnu.tar.xz -o - | tar xJ -C extended-vft/target/tmp

    - name: Run tests
      run: cargo test --manifest-path extended-vft/Cargo.toml

  