name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true

    - name: Install Clippy
      run: rustup component add clippy

    - name: Install Rustfmt
      run: rustup component add rustfmt

    - name: Install rust-src component
      run: rustup component add rust-src --toolchain stable-x86_64-unknown-linux-gnu

    - name: Check formatting
      run: cargo fmt --all --check

    - name: Run Clippy
      run: cargo clippy -r --all -- -D warnings

    - name: Prepare environment
      run: |
        mkdir -p target/tmp
        curl -L https://get.gear.rs/gear-v1.6.1-x86_64-unknown-linux-gnu.tar.xz -o - | tar xJ -C target/tmp

    - name: Run tests
      run: cargo test -r --all -- --ignored

    - name: Build for WASM
      run: cargo build --release --target wasm32-unknown-unknown

    - name: Collect artifacts
      run: |
        mkdir -p artifacts
        cp target/wasm32-unknown-unknown/release/*.wasm artifacts/
        cp target/wasm32-unknown-unknown/release/*.idl artifacts/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: artifacts/*

    - name: Publish artifacts to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Publishing artifacts to GitHub Packages"
        mkdir -p packages
        for file in artifacts/*; do
          filename=$(basename "$file")
          curl -u "${{ secrets.GITHUB_ACTOR }}:${{ secrets.GITHUB_TOKEN }}" \
            -X POST \
            -H "Content-Type: application/octet-stream" \
            --data-binary @"$file" \
            https://api.github.com/repos/${{ github.repository }}/packages \
            -H "Accept: application/vnd.github.v3+json"
        done
